---
- name: mysqld ExecStartPre
  command: /usr/bin/mysqld_pre_systemd
  changed_when: false
- name: Check mysqld pid file
  stat:
    path: /var/run/mysqld/mysqld.pid
  register: mysqld_pid
  changed_when: false
- name: boot MySQL on Docker
  command: "sudo -u mysql /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid --explicit_defaults_for_timestamp"
  when: not mysqld_pid.stat.exists
