---
# handlers file for apache_passenger
- name: Restart apache docker
  become: yes
  command: /usr/sbin/httpd -k graceful
  changed_when: false
  when: is_docker.stdout | bool
- name: Restart apache systemd
  become: yes
  systemd:
    name: httpd
    state: restarted
  when: not is_docker.stdout | bool
